import bs4 as bs
import re
from selenium import webdriver
import time

def pauseva():
	for i in range(1,16):
		time.sleep(1)
		print i
	return

SCROLL_PAUSE_TIME = 5

url = 'https://www.flipkart.com/offers/deals-of-the-day?pk=dotd'

driver = webdriver.Firefox()
driver.get(url)           

#driver.execute_script("window.scrollTo(0, document.body.scrollHeight/5)")
#pauseva()

# SCROLLING TO LOAD THE HTML GENERATED BY JAVASCRIPT
driver.execute_script("window.scrollTo(0, document.body.scrollHeight/4)")
pauseva()
driver.execute_script("window.scrollTo(0, document.body.scrollHeight/3)")
pauseva()
driver.execute_script("window.scrollTo(0, document.body.scrollHeight/2)")
pauseva()

html = driver.page_source
soup = bs.BeautifulSoup(html,"html.parser")


# GETTING NAME AND DAILY PRICES
div = soup.find_all('div', attrs={'class' : 'iUmrbN'})
div2 = soup.find_all('div', attrs={'class' : 'BXlZdc'})

#for i in range(0,len(div)):
#	item = div[0].find_all('div', text)

name = []
discount = []
for i in range(0,len(div)):
	name.append(div[i].text)
	discount.append(div2[i].text)

	print name[i] + "," + discount[i]
	



driver.close()
